#!/bin/bash
# Generates the scripts required to perform a CodeDeploy deployment
# for your project.
set -eou pipefail

SCRIPT_DIR=$(dirname $0)

# VARIABLES
AWS_PROFILE="$1"; shift
AWS_REGION="$1"; shift
IMAGE="$1"; shift
SERVICE="$1"; shift
CLUSTER="$1"; shift
TASK_DEF="$1"; shift
DOCKER_ROOT="$1"; shift
DEPLOY_APP="$1"; shift
DEPLOY_GRP="$1"; shift
DEPLOY_SPEC="$1"; shift
DEPLOYMENT_FOLDER="$1"; shift

FILE_TASK_DEF="${DEPLOYMENT_FOLDER}/task-def.json"
FILE_DEPLOY_SPEC="${DEPLOYMENT_FOLDER}/deploy-spec.json"

if [ -d ${DEPLOYMENT_FOLDER} ]; then
  echo "Deployment already exists."
  exit 0
fi

mkdir -p ${DEPLOYMENT_FOLDER}

cat <<EOF > ${DEPLOYMENT_FOLDER}/deploy.conf
# deploy.conf
# Automatically generated by Terraform ECS HA module.
# Do not manually edit this file unless you know what you're doing.

CWD=\$(pwd)
AWS_PROFILE=${AWS_PROFILE?"Not defined"}
AWS_REGION=${AWS_REGION?"Not defined"}
DOCKER_FOLDER=${DOCKER_ROOT?"Not defined"}
DOCKER_IMAGE=${IMAGE?"Not defined"}
ECS_SERVICE=${SERVICE?"Not defined"}
ECS_CLUSTER=${CLUSTER?"Not defined"}
ECS_DEPLOY_APP=${DEPLOY_APP?"Not defined"}
ECS_DEPLOY_GRP=${DEPLOY_GRP?"Not defined"}
ECS_FILE_TASK_DEF=\${CWD}/task-def.json
ECS_FILE_DEPLOY_SPEC=\${CWD}/deploy-spec.json
EOF

echo "${TASK_DEF}" > ${FILE_TASK_DEF}
echo "${DEPLOY_SPEC}" > ${FILE_DEPLOY_SPEC}

cp ${SCRIPT_DIR}/aws-code-deploy.sh ${DEPLOYMENT_FOLDER}/deploy.sh
chmod +x ${DEPLOYMENT_FOLDER}/deploy.sh

echo "Deployment folder generated at ${DEPLOYMENT_FOLDER}"
exit 0